version: '3.9'
services:
  backend:
    image: ghcr.io/cybercitizen01/freemex-backend:${APP_IMG_TAG:-latest}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
    depends_on:
      - db
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
  db:
    image: postgres:${PG_IMG_TAG:-13.4-alpine}
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  db-data:
